/*
 * cert.c
 *
 *  Created on: 27.11.2018
 *      Author: Mario
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>

const char *server_root_cert = "-----BEGIN CERTIFICATE-----\n"
		"MIIDfDCCAmSgAwIBAgIJAKx+Hcw9SbFRMA0GCSqGSIb3DQEBCwUAMFMxETAPBgNV\n"
		"BAMMCDEwLjAuMC4xMQwwCgYDVQQKDANTTUMxDDAKBgNVBAsMA0dUQzEiMCAGCSqG\n"
		"SIb3DQEJARYTbWlvc2dhLm1hcmlvQHNtYy5kZTAeFw0xODExMjIwOTMxMzJaFw0z\n"
		"MjExMTgwOTMxMzJaMFMxETAPBgNVBAMMCDEwLjAuMC4xMQwwCgYDVQQKDANTTUMx\n"
		"DDAKBgNVBAsMA0dUQzEiMCAGCSqGSIb3DQEJARYTbWlvc2dhLm1hcmlvQHNtYy5k\n"
		"ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANlOBK5o4gIPlgMUfxkD\n"
		"GD/EB5y4M2+L/h4mt2adsRkLnd9uIJ1IRSVZwHUKZe4mNWFjvUFE8Xf3RpjYSqJf\n"
		"SheCTAf2WOaLYfWbCbd/+QBa65/Wnng0nQ0Q99iv/TW2ssw2bsRJlllV/tJ88EnY\n"
		"YfLDF+0TFdurlQO7NQxLyuyVl5HuFerL/ODCB/Bkd0lswcVKe208UV9g3Ua62hkb\n"
		"f5DG/TVAAvRF8tyNweFDVWE/FHf6EfXmbF/0fiIVAL7zBEFL5U/OLwQbwOXrYsMp\n"
		"qYDKoPKGki7Tk19/XNb5dU7tpKorCSpqu+U+D6+q1bQHcTywF6D1evgUdLw4JXzG\n"
		"sHUCAwEAAaNTMFEwHQYDVR0OBBYEFGq4j2lMF0oOqZ9wJvV11/UNFxjUMB8GA1Ud\n"
		"IwQYMBaAFGq4j2lMF0oOqZ9wJvV11/UNFxjUMA8GA1UdEwEB/wQFMAMBAf8wDQYJ\n"
		"KoZIhvcNAQELBQADggEBAD++Id++VZSWcscRGMcoQnNXTriPJHQQ2LW4MltiDyYt\n"
		"3a+ZPPRs5C5NX8VBlavg5rDFDP3QUjG3ezdazBmPBY52dsRyRieOJOQyHc6w8UhO\n"
		"bV/XctVN8aLeTdLGpYrPKDHsskz8It4m/xVxgr0PBLOHPNnZgqcmw6pt7oGXegug\n"
		"YlZJaUjIuiRwALiNBXK6ICuYt1nwJmXQWGEcbNBHe851dZM6iUTp0wWeqEVS9zK4\n"
		"jqRAJwWzM+0SEXyLc2VQZeUneP11DaDAamZ/5Q1xU14YjuCRdY/rDGzgcwwF/3nU\n"
		"E8icmvakU2P05eyFOR87j70WVLJ7lBGZrjQNnW6XfSY=\n"
		"-----END CERTIFICATE-----\n";

